Modal
Bludidi/Portfolio-Desktop-version- pull request #19
Opened 2022-09-16 08:41 UTC by Bludidi

# In this pull request we:
- Refactored HTML file.
- Created project cards dynamically using javascript. 
- Created a popup window that shows the information of each project. 
- The popup window is for both desktop and mobile devices.
- correctly set git workflow.
- check linter errors.
- followed best practices.

2022-09-16 10:26 UTC, Abenezer-Tilahun requested changes
Hi @Bludidi 

Good job so far 👏!
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Highlights

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional README 

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 10:26 UTC, Abenezer-Tilahun commented on main.js
> +        </div>
- [ ] Kindly follow  design for  mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins). Please try to adjust the alignment based on the Figma design.
The Figma design Look likes: 
![Capt3](https://user-images.githubusercontent.com/93598189/190614692-80cd020b-3002-4afb-a4c6-681fbd124dac.PNG)

Your design Look Likes : 
![Capt4](https://user-images.githubusercontent.com/93598189/190614880-a4a84a8e-f9d1-4776-9365-fadcee6766a4.PNG)

2022-09-16 10:26 UTC, Abenezer-Tilahun commented on main.js
> +            <a href="${projects[index].seeSource}">See Source <i class="close"></i></a>
- [ ] Kindly follow design for Desktop and  mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins). Please try to add the icon for "See Live" and " See Source" based on the Figma design.
The Figma design Look likes:
![Capture1](https://user-images.githubusercontent.com/93598189/190616025-21b8a213-0a52-40fc-88cd-0421a0cb6145.PNG)

Your Design Look Likes This  : 
![Capture](https://user-images.githubusercontent.com/93598189/190616098-54d9e2d1-b93f-4a04-a3d2-56982756f17d.PNG)

2022-09-16 10:26 UTC, Abenezer-Tilahun commented on main.js
> +            <a href="${projects[index].seeSource}">See Source <i class="close"></i></a>
- [ ]   Kindly Adjust "Popup Cards" size to fit to mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) to make the popup responsive.
The Figma design Look Likes: 
![temp](https://user-images.githubusercontent.com/93598189/190617178-e476e65a-643e-4214-ba47-5c57689f3b06.PNG)

Your Design Look likes this : 
![Capt123](https://user-images.githubusercontent.com/93598189/190617434-bed37542-bb9e-4748-aa6a-dd6ac5e94dc4.PNG)

2022-09-16 18:04 UTC, BenMukebo requested changes
Hi @Bludidi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Please it will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser. You can put the steps to clone and run the project in a new Getting Started section under the project's description.


- [OPTIONAL ] Linters are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practices. Please Instead of disabling the client, it will be nice to fix all linter errors manually.

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 18:04 UTC, BenMukebo commented on main.js
> +
- [ ] Kindly follow  design for  mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins). Please try to adjust the alignment based on the Figma design.

| Your design | Figma design |
| --- | --- |
| ![Capt4](https://user-images.githubusercontent.com/93598189/190614880-a4a84a8e-f9d1-4776-9365-fadcee6766a4.PNG) | ![Capt3](https://user-images.githubusercontent.com/93598189/190614692-80cd020b-3002-4afb-a4c6-681fbd124dac.PNG) |

- [ ] Kindly Address this 🙃 

_Originally posted by @Abenezer-Tilahun in https://github.com/Bludidi/Portfolio-Desktop-version-/pull/19#discussion_r972864054_

2022-09-16 18:04 UTC, BenMukebo commented on main.js
> +          </div>
- [ ] The `See live`, and `See Source` buttons of your popup window should be close to the original design Check the [templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) Kindly follow the original vision, you have to use the same font, colors (background and font) and the same margins (top, bottom, left, right) defined in the design if it's pretty and works, it will be a wonderful website. 🎨 🖌️ 

| Your design | Figma design |
| --- | --- |
|![18](https://user-images.githubusercontent.com/79058364/190692126-1a5a995f-2241-483c-9b49-3cb177f46afe.png) | ![18](https://user-images.githubusercontent.com/79058364/190692245-15148118-7125-4e25-b0ef-d9337c09b93c.png)
|

2022-09-16 18:04 UTC, BenMukebo commented on modal.css
> +}
- [OPTIONAL] What about preventing the sub-background from scrolling when the navbar is open? You can use a CSS property `over-flow: hidden;` to do that, which will make your mobile menu correspond to the original design.💯 🥇

2022-09-16 18:04 UTC, BenMukebo commented on main.js
> +  });
- [ ] As requested by the previous reviewer [here](https://github.com/Bludidi/Portfolio-Desktop-version-/pull/19#discussion_r972874828) Kindly Adjust the "Popup Cards" size to fit mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) to make the popup responsive. Let's increase the width of the image

| Your design | Figma design |
| --- | --- |
| ![18](https://user-images.githubusercontent.com/79058364/190702170-47e56b8f-1e0a-4df3-bd2d-2bac6cb00e16.png) | ![18](https://user-images.githubusercontent.com/79058364/190701945-a054441c-e2ba-4ddb-afb7-579b2802f4f8.png) |

2022-09-17 06:51 UTC, Bludidi commented on main.js
> +  });
@BenMukebo Hello my brother, when you say "Adjust the "Popup Cards" size to fit mobile versions" do you mean the height?

2022-09-17 07:22 UTC, topeogunleye commented on main.js
> +  });
@Bludidi, I think the best solution is to use media queries to set different images for the Mobile Design. If you check the Figma design, the images and aspect ratios of the portfolio images are different for desktop and mobile respectively,

2022-09-17 07:35 UTC, Bludidi commented on main.js
> +  });
@topeogunleye too bad I already requested a review, is there a way I can cancel the request?

2022-09-17 07:35 UTC, topeogunleye requested changes
Hi @Bludidi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:
* PR has a good title and summary :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 07:35 UTC, topeogunleye commented on main.js
> +  });
- [ ] As suggested by the previous code reviewer. I kindly suggest that you work on making the image take it's maximum width like it does for desktop. I think the best solution is to use the bigger image i.e desktop images for your projects. You can download them from the Figma design

| Your Design  | Figma Design  | 
| ------------- |-------------:  |
| <img width="219" alt="image" src="https://user-images.githubusercontent.com/52934128/190845923-af3e7a9b-664e-4889-b461-b41fb2b5c340.png">     | ![190701945-a054441c-e2ba-4ddb-afb7-579b2802f4f8](https://user-images.githubusercontent.com/52934128/190845931-5a179ce4-92d3-41c9-81e2-3bc82cc3924b.png)   |

2022-09-17 07:37 UTC, Bludidi commented on main.js
> +  });
@topeogunleye have put all my focus on the functionality of the code and now I really feel less motivated plus I have to finish some other projects as well.

2022-09-17 07:44 UTC, topeogunleye commented on modal.css
> +  height: 50%;
- [ ] I kindly suggest you remove this property of height: 50% as it will make your image take it's full width.

2022-09-17 11:20 UTC, EricMbouwe approved these changes
Hi @Bludidi, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- requested changes ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 11:23 UTC, merged